exclude:
  - "**/dist/**/*"
  - "**/*.patch"
  - "**/node_modules/**/*"
  - "**/vendor/**/*"
  - ".github/workflows/**/*" # https://github.com/restyled-io/restyler/issues/73

restylers:
  - clang-format:
      enabled: false
  - jq:
      enabled: false # prefer prettier-json
  - prettier:
      include:
        - 'src/**/*.js'
