name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn gen-flow
      - run: yarn lint
      - run: yarn test
      - run: yarn run check-git-clean
